Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjGura.Models;

namespace prjGura.Controllers
{
    public class ClientesController : Controller
    {
        private readonly PostgresContext _context;

        public ClientesController(PostgresContext context)
        {
            _context = context;
        }

        // GET: Clientes
        public async Task<IActionResult> Index()
        {
            return View(await _context.Clientes.ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Cpf == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cpf,Nome,Telefone,QuantidadePets")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Cpf,Nome,Telefone,QuantidadePets")] Cliente cliente)
        {
            if (id != cliente.Cpf)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ClienteExists(cliente.Cpf))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .FirstOrDefaultAsync(m => m.Cpf == id);
            if (cliente == null)
            {
                return NotFound();
            }

            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente != null)
            {
                _context.Clientes.Remove(cliente);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ClienteExists(string id)
        {
            return _context.Clientes.Any(e => e.Cpf == id);
        }
    }
}

Controllers/EstoqueController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjGura.Models;

namespace prjGura.Controllers
{
    public class EstoqueController : Controller
    {
        private readonly PostgresContext _context;

        public EstoqueController(PostgresContext context)
        {
            _context = context;
        }

        // GET: Estoque
        public async Task<IActionResult> Index()
        {
            var postgresContext = _context.Produtosfornecidos.Include(p => p.IdfornecedorNavigation).Include(p => p.IdprodutoNavigation);
            return View(await postgresContext.ToListAsync());
        }

        // GET: Estoque/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtosfornecido = await _context.Produtosfornecidos
                .Include(p => p.IdfornecedorNavigation)
                .Include(p => p.IdprodutoNavigation)
                .FirstOrDefaultAsync(m => m.Idproduto == id);
            if (produtosfornecido == null)
            {
                return NotFound();
            }

            return View(produtosfornecido);
        }

        // GET: Estoque/Create
        public IActionResult Create()
        {
            ViewData["Idfornecedor"] = new SelectList(_context.Fornecedors, "Cnpj", "Cnpj");
            ViewData["Idproduto"] = new SelectList(_context.Produtos, "Id", "Id");
            return View();
        }

        // POST: Estoque/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Idproduto,Idfornecedor,PrecoCusto,Quantidade,Data")] Produtosfornecido produtosfornecido)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produtosfornecido);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idfornecedor"] = new SelectList(_context.Fornecedors, "Cnpj", "Cnpj", produtosfornecido.Idfornecedor);
            ViewData["Idproduto"] = new SelectList(_context.Produtos, "Id", "Id", produtosfornecido.Idproduto);
            return View(produtosfornecido);
        }

        // GET: Estoque/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtosfornecido = await _context.Produtosfornecidos.FindAsync(id);
            if (produtosfornecido == null)
            {
                return NotFound();
            }
            ViewData["Idfornecedor"] = new SelectList(_context.Fornecedors, "Cnpj", "Cnpj", produtosfornecido.Idfornecedor);
            ViewData["Idproduto"] = new SelectList(_context.Produtos, "Id", "Id", produtosfornecido.Idproduto);
            return View(produtosfornecido);
        }

        // POST: Estoque/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Idproduto,Idfornecedor,PrecoCusto,Quantidade,Data")] Produtosfornecido produtosfornecido)
        {
            if (id != produtosfornecido.Idproduto)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produtosfornecido);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProdutosfornecidoExists(produtosfornecido.Idproduto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Idfornecedor"] = new SelectList(_context.Fornecedors, "Cnpj", "Cnpj", produtosfornecido.Idfornecedor);
            ViewData["Idproduto"] = new SelectList(_context.Produtos, "Id", "Id", produtosfornecido.Idproduto);
            return View(produtosfornecido);
        }

        // GET: Estoque/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produtosfornecido = await _context.Produtosfornecidos
                .Include(p => p.IdfornecedorNavigation)
                .Include(p => p.IdprodutoNavigation)
                .FirstOrDefaultAsync(m => m.Idproduto == id);
            if (produtosfornecido == null)
            {
                return NotFound();
            }

            return View(produtosfornecido);
        }

        // POST: Estoque/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produtosfornecido = await _context.Produtosfornecidos.FindAsync(id);
            if (produtosfornecido != null)
            {
                _context.Produtosfornecidos.Remove(produtosfornecido);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProdutosfornecidoExists(int id)
        {
            return _context.Produtosfornecidos.Any(e => e.Idproduto == id);
        }
    }
}

Controllers/FornecedorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using prjGura.Models;

namespace prjGura.Controllers
{
    public class FornecedorsController : Controller
    {
        private readonly PostgresContext _context;

        public FornecedorsController(PostgresContext context)
        {
            _context = context;
        }

        // GET: Fornecedors
        public async Task<IActionResult> Index()
        {
            return View(await _context.Fornecedors.ToListAsync());
        }

        // GET: Fornecedors/Details/5
        public async Task<IActionResult> Details(string id)
        {
            var cnpjDecodificado = HttpUtility.UrlDecode(id);
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedors
                .FirstOrDefaultAsync(m => m.Cnpj == cnpjDecodificado);
            if (fornecedor == null)
            {
                return NotFound();
            }
            var listprdforn = _context.Produtosfornecidos.Where(x => x.Idfornecedor == fornecedor.Cnpj).ToList();

            fornecedor.Produtosfornecidos = listprdforn;

            return View(fornecedor);
        }

        // GET: Fornecedors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Fornecedors/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Cnpj,RazaoSocial,Telefone,Endereco")] Fornecedor fornecedor)
        {
            if (ModelState.IsValid)
            {
                _context.Add(fornecedor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        // GET: Fornecedors/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedors.FindAsync(id);
            if (fornecedor == null)
            {
                return NotFound();
            }
            return View(fornecedor);
        }

        // POST: Fornecedors/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Cnpj,RazaoSocial,Telefone,Endereco")] Fornecedor fornecedor)
        {
            if (id != fornecedor.Cnpj)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(fornecedor);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FornecedorExists(fornecedor.Cnpj))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(fornecedor);
        }

        // GET: Fornecedors/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var fornecedor = await _context.Fornecedors
                .FirstOrDefaultAsync(m => m.Cnpj == id);
            if (fornecedor == null)
            {
                return NotFound();
            }

            return View(fornecedor);
        }

        // POST: Fornecedors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var fornecedor = await _context.Fornecedors.FindAsync(id);
            if (fornecedor != null)
            {
                _context.Fornecedors.Remove(fornecedor);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FornecedorExists(string id)
        {
            return _context.Fornecedors.Any(e => e.Cnpj == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PetHub</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <style>
        body {
            height: 100vh;
            display: flex;
            flex-direction: column;
        }

        .sidebar {
            height: 100vh;
            position: fixed;
            background-color: #f8f9fa; /* Cor neutra */
            border-right: 1px solid #dee2e6; /* Linha de separação */
            padding-top: 20px;
        }

            .sidebar .nav-link {
                color: #495057; /* Cinza escuro para os links */
                font-weight: 500;
            }

                .sidebar .nav-link:hover {
                    color: #212529; /* Cinza mais escuro para hover */
                    background-color: #e9ecef; /* Fundo suave no hover */
                    border-radius: 5px;
                }

        .main-content {
            margin-left: 250px; /* Largura fixa do menu lateral */
            padding: 20px;
        }
    </style>
</head>
<body>
    <header>
        <nav class="sidebar d-flex flex-column align-items-start p-3">
            <a class="navbar-brand mb-4" href="#" style="font-weight: bold; font-size: 1.5rem;">PetHub</a>
            <ul class="nav flex-column w-100">
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Funcionarios" asp-action="Index">Funcionários</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Produtos" asp-action="Index">Produtos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Produtos" asp-action="Vendas">Vendas</a>
                </li>
                <li class="nav-item">
                    <div class="dropdown w-100">
                        <button class="btn btn-outline-secondary dropdown-toggle w-100 text-start"
                                type="button"
                                id="dropdownMenuButton"
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                            Agendamento
                        </button>
                        <ul class="dropdown-menu w-100" aria-labelledby="dropdownMenuButton">
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Index">Geral</a>
                            </li>
                            <li>
                                <a class="dropdown-item" asp-area="" asp-controller="Vendas" asp-action="Index">Cliente</a>
                            </li>
                        </ul>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Estoque" asp-action="Index">Estoque</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" asp-area="" asp-controller="Fornecedors" asp-action="Index">Fornecedores</a>
                </li>
            </ul>
        </nav>
    </header>
    <main class="main-content">
        <div class="container">
            <div class="pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">@ViewData["Title"]</h1>
            </div>
            <div>
                @RenderBody()
            </div>
        </div>
    </main>
    <footer class="border-top footer text-muted mt-auto">
        <div class="container">
            &copy; 2024 - PetHub
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>